import { Check, CircleHelp, ShieldCheck, Sparkles, TrendingDown, TrendingUp } from 'lucide-react';
import type { AgentDecision, AgentStatus, RiskCheck } from '../lib/api';

export function AgentCoach({ status, decision, risk, processing, stage, onRun }: { status: AgentStatus; decision?: AgentDecision; risk?: RiskCheck; processing: boolean; stage: string; onRun: () => void }) {
  const hasRisk = Boolean(risk);
  const isRejected = risk?.status === 'REJECTED';
  const explanation = processing ? 'The agent is checking the event, market context, and risk limits now.' : decision ? isRejected ? 'The agent found a possible setup, but the independent risk controls blocked the paper order.' : 'The agent finished its review. Read the thesis and risk check before running another scenario.' : 'Start a demo analysis to see how an event becomes a transparent paper-trading decision.';
  return <section className="agent-coach"><div className="agent-coach-main"><div className="agent-coach-icon"><CircleHelp size={18} /></div><div><div className="agent-coach-kicker">HOW TO READ THIS AGENT</div><h3>{processing ? 'Analysis in progress' : decision ? 'Review complete' : 'Your trading co-pilot is ready'}</h3><p>{explanation}</p></div><button className="primary-button agent-coach-action" onClick={onRun} disabled={processing}><Sparkles size={14} /> {processing ? 'CHECKING...' : decision ? 'RUN NEW ANALYSIS' : 'RUN DEMO ANALYSIS'}</button></div><div className="agent-coach-steps"><div className={stage === 'EVENT_DETECTED' || processing ? 'current' : 'done'}><span>1</span><strong>Read event</strong><small>What changed?</small></div><div className={stage === 'CONTEXT_ANALYSIS' || stage === 'AI_DECISION' ? 'current' : decision ? 'done' : ''}><span>2</span><strong>Check context</strong><small>Trend + indicators</small></div><div className={stage === 'RISK_CHECK' ? 'current' : risk ? 'done' : ''}><span>3</span><strong>Control risk</strong><small>Position limits</small></div><div className={risk ? (isRejected ? 'blocked' : 'done') : ''}><span>{risk ? (isRejected ? '!' : <Check size={12} />) : '4'}</span><strong>{risk ? (isRejected ? 'Blocked safely' : 'Paper decision') : 'Decision'}</strong><small>{risk ? (isRejected ? 'No order placed' : 'Ready to inspect') : 'Coming next'}</small></div></div><div className={`agent-coach-status ${isRejected ? 'warning' : risk ? 'good' : ''}`}>{isRejected ? <TrendingDown size={14} /> : risk ? <ShieldCheck size={14} /> : <TrendingUp size={14} />}<span><strong>{risk ? (isRejected ? 'Risk controls stopped this order' : 'Risk controls passed') : 'Independent risk controls are always applied'}</strong><small>{risk ? risk.reasons[0] ?? 'See the risk check below for the full explanation.' : 'AI proposes an action; deterministic rules make the final safety decision.'}</small></span></div></section>;
}
