import { useEffect, useMemo, useRef, useState } from 'react';
import { CandlestickSeries, CrosshairMode, HistogramSeries, LineSeries, createChart, type IChartApi, type UTCTimestamp } from 'lightweight-charts';
import type { MarketSnapshot } from '../lib/api';
export const LIVE_GRAPH_RANGES = ['1M', '5M', '15M', '1H', '1D', '1W'] as const;
export type LiveGraphRange = (typeof LIVE_GRAPH_RANGES)[number];
export type LiveGraphView = 'candles' | 'line';
export type GraphPoint = { timestamp: string; price: number; open?: number; high?: number; low?: number; close?: number; volume?: number };
type Candle = { time: UTCTimestamp; open: number; high: number; low: number; close: number; volume: number };
type Tooltip = Candle & { x: number; y: number };
const intervalSeconds: Record<LiveGraphRange, number> = { '1M': 60, '5M': 300, '15M': 900, '1H': 3600, '1D': 86400, '1W': 604800 };
export const historyWindow: Record<LiveGraphRange, string> = { '1M': '1M', '5M': '5M', '15M': '15M', '1H': '1H', '1D': '1D', '1W': '1W' };
function toCandles(points: GraphPoint[], range: LiveGraphRange): Candle[] {
  const bucketSize = intervalSeconds[range]; const buckets = new Map<number, Candle>();
  [...points].sort((a, b) => Date.parse(a.timestamp) - Date.parse(b.timestamp)).forEach((point) => {
    const seconds = Math.floor(Date.parse(point.timestamp) / 1000); if (!Number.isFinite(seconds) || !Number.isFinite(point.price) || point.price <= 0) return;
    const bucket = Math.floor(seconds / bucketSize) * bucketSize; const close = point.close && point.close > 0 ? point.close : point.price; const open = point.open && point.open > 0 ? point.open : close; const high = point.high && point.high > 0 ? point.high : close; const low = point.low && point.low > 0 ? point.low : close; const previous = buckets.get(bucket);
    if (!previous) buckets.set(bucket, { time: bucket as UTCTimestamp, open, high, low, close, volume: point.volume ?? 0 });
    else buckets.set(bucket, { time: previous.time, open: previous.open, high: Math.max(previous.high, high, close), low: Math.min(previous.low, low, close), close, volume: previous.volume + (point.volume ?? 0) });
  });
  return [...buckets.values()].filter((candle) => candle.open > 0 && candle.high >= candle.low && candle.close > 0).sort((a, b) => Number(a.time) - Number(b.time));
}
function formatPrice(value: number) { if (value < 0.01) return value.toFixed(8); if (value < 10) return value.toFixed(4); return value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function formatTime(value: UTCTimestamp) { return new Date(Number(value) * 1000).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }); }
export function LiveMarketGraph({ symbol, symbols, points, quote, range, onRangeChange, liveState, lastUpdated, onSymbolChange }: { symbol: string; symbols: string[]; points: GraphPoint[]; quote: MarketSnapshot; range: LiveGraphRange; onRangeChange: (range: LiveGraphRange) => void; liveState: 'CONNECTING' | 'LIVE' | 'STALE'; lastUpdated: string | null; onSymbolChange: (symbol: string) => void }) {
  const chartHost = useRef<HTMLDivElement>(null); const chartRef = useRef<IChartApi | null>(null); const candleSeriesRef = useRef<any>(null); const lineSeriesRef = useRef<any>(null); const volumeSeriesRef = useRef<any>(null); const [view, setView] = useState<LiveGraphView>('candles'); const [tooltip, setTooltip] = useState<Tooltip | null>(null); const candles = useMemo(() => toCandles(points, range), [points, range]); const current = candles[candles.length - 1];
  useEffect(() => { if (!chartHost.current) return; const chart = createChart(chartHost.current, { autoSize: true, layout: { background: { color: '#0f172a' }, textColor: '#8ca0b5', fontFamily: 'DM Mono, monospace', fontSize: 10 }, grid: { vertLines: { color: '#17263a' }, horzLines: { color: '#17263a' } }, crosshair: { mode: CrosshairMode.Normal, vertLine: { color: '#4f718a', width: 1, style: 3 }, horzLine: { color: '#4f718a', width: 1, style: 3 } }, rightPriceScale: { borderColor: '#25384c', autoScale: true }, timeScale: { borderColor: '#25384c', timeVisible: true, secondsVisible: false, rightOffset: 3 } }); const candlesSeries = chart.addSeries(CandlestickSeries, { upColor: '#22c55e', downColor: '#ef4444', borderUpColor: '#22c55e', borderDownColor: '#ef4444', wickUpColor: '#22c55e', wickDownColor: '#ef4444' }); const lineSeries = chart.addSeries(LineSeries, { color: '#38bdf8', lineWidth: 2, crosshairMarkerVisible: true }); const volumeSeries = chart.addSeries(HistogramSeries, { priceFormat: { type: 'volume' }, priceScaleId: '', color: 'rgba(34,197,94,.34)' }); volumeSeries.priceScale().applyOptions({ scaleMargins: { top: .84, bottom: 0 } }); const handleCrosshair = (param: any) => { const data = param.seriesData?.get(candlesSeries); if (!data || !param.point || typeof data.open !== 'number' || typeof data.high !== 'number' || typeof data.low !== 'number' || typeof data.close !== 'number' || typeof data.time !== 'number') { setTooltip(null); return; } setTooltip({ ...data, volume: typeof data.volume === 'number' ? data.volume : 0, x: Math.min(Math.max(param.point.x + 14, 8), (chartHost.current?.clientWidth ?? 500) - 205), y: Math.min(Math.max(param.point.y - 88, 8), (chartHost.current?.clientHeight ?? 280) - 128) }); }; chart.subscribeCrosshairMove(handleCrosshair); chartRef.current = chart; candleSeriesRef.current = candlesSeries; lineSeriesRef.current = lineSeries; volumeSeriesRef.current = volumeSeries; const resize = new ResizeObserver(() => chart.resize(chartHost.current?.clientWidth ?? 600, chartHost.current?.clientHeight ?? 300)); resize.observe(chartHost.current); return () => { resize.disconnect(); chart.unsubscribeCrosshairMove(handleCrosshair); chart.remove(); chartRef.current = null; }; }, []);
  useEffect(() => { const chart = chartRef.current; const candlesSeries = candleSeriesRef.current; const lineSeries = lineSeriesRef.current; const volumeSeries = volumeSeriesRef.current; if (!chart || !candlesSeries || !lineSeries || !volumeSeries) return; candlesSeries.setData(candles); lineSeries.setData(candles.map((candle) => ({ time: candle.time, value: candle.close }))); volumeSeries.setData(candles.map((candle) => ({ time: candle.time, value: candle.volume, color: candle.close >= candle.open ? 'rgba(34,197,94,.35)' : 'rgba(239,68,68,.35)' }))); candlesSeries.applyOptions({ visible: view === 'candles' }); lineSeries.applyOptions({ visible: view === 'line' }); if (candles.length) chart.timeScale().fitContent(); }, [candles, view]);
  return <div className="live-market-graph"><div className="live-graph-toolbar"><div className="live-graph-pair"><label htmlFor={`market-pair-${symbol}`}>MARKET</label><select id={`market-pair-${symbol}`} value={symbol} onChange={(event) => onSymbolChange(event.target.value)}>{symbols.map((item) => <option key={item} value={item}>{item}/USDT</option>)}</select></div><div className="live-graph-price"><strong>{formatPrice(quote.price)}</strong><span className={quote.changePct >= 0 ? 'gain' : 'loss'}>{quote.changePct >= 0 ? '+' : ''}{quote.changePct.toFixed(2)}%</span></div><span className={`live-graph-status ${liveState.toLowerCase()}`}><i /> {liveState === 'LIVE' ? 'LIVE · BITGET CANDLES' : liveState}{lastUpdated && <small>{new Date(lastUpdated).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</small>}</span></div><div className="live-graph-controls"><div className="live-graph-ranges">{LIVE_GRAPH_RANGES.map((item) => <button type="button" key={item} className={range === item ? 'active' : ''} onClick={() => onRangeChange(item)}>{item}</button>)}</div><div className="live-graph-view"><button type="button" className={view === 'candles' ? 'active' : ''} onClick={() => setView('candles')}>CANDLES</button><button type="button" className={view === 'line' ? 'active' : ''} onClick={() => setView('line')}>LINE</button></div></div><div className="live-graph-canvas" ref={chartHost}>{tooltip && <div className="live-graph-tooltip" style={{ left: tooltip.x, top: tooltip.y }}><strong>{formatTime(tooltip.time)}</strong><span>O <b>{formatPrice(tooltip.open)}</b></span><span>H <b>{formatPrice(tooltip.high)}</b></span><span>L <b>{formatPrice(tooltip.low)}</b></span><span>C <b>{formatPrice(tooltip.close)}</b></span><span>VOL <b>{tooltip.volume.toLocaleString()}</b></span></div>}{!candles.length && <div className="live-graph-empty">Waiting for live market data…</div>}</div><div className="live-graph-footer"><span>Bitget USDT perpetual · Zoom and pan with your mouse or touchpad</span><span>{current ? `Last close ${formatPrice(current.close)}` : 'No candle yet'}</span></div></div>;
}
