import { db } from './database.js';
import { rowToEvent } from '../engine/eventEngine.js';
import { getMarketSnapshot, SUPPORTED_SYMBOLS } from '../engine/marketData.js';
import type { AgentDecision, AgentStatus, AuditLog, MarketEvent, MarketSnapshot, PortfolioSummary, Position, RiskCheck, Trade } from '../types.js';

export function getEvents(limit = 50): MarketEvent[] { return (db.prepare('SELECT * FROM events ORDER BY timestamp DESC LIMIT ?').all(limit) as Record<string, unknown>[]).map(rowToEvent); }
export function getEvent(id: string): MarketEvent | undefined { const row = db.prepare('SELECT * FROM events WHERE id = ?').get(id) as Record<string, unknown> | undefined; return row ? rowToEvent(row) : undefined; }
export function getDecisions(limit = 50): AgentDecision[] { return (db.prepare('SELECT * FROM agent_decisions ORDER BY created_at DESC LIMIT ?').all(limit) as Record<string, unknown>[]).map((row) => ({ id: String(row.id), eventId: String(row.event_id), symbol: String(row.symbol), action: row.action as AgentDecision['action'], confidence: Number(row.confidence), eventImpact: row.event_impact as AgentDecision['eventImpact'], timeHorizon: String(row.time_horizon), thesis: String(row.thesis), riskFactors: JSON.parse(String(row.risk_factors)), suggestedPositionPercent: Number(row.suggested_position_percent), stopLossPercent: Number(row.stop_loss_percent), takeProfitPercent: Number(row.take_profit_percent), rationale: String(row.rationale), createdAt: String(row.created_at) })); }
export function getDecision(id: string): AgentDecision | undefined { return getDecisions(1000).find((decision) => decision.id === id); }
export function getTrades(limit = 50): Trade[] { return (db.prepare('SELECT * FROM orders ORDER BY timestamp DESC LIMIT ?').all(limit) as Record<string, unknown>[]).map((row) => ({ id: String(row.id), decisionId: row.decision_id ? String(row.decision_id) : undefined, symbol: String(row.symbol), side: row.side as Trade['side'], quantity: Number(row.quantity), price: Number(row.price), notional: Number(row.notional), confidence: Number(row.confidence), riskScore: Number(row.risk_score), status: row.status as Trade['status'], realizedPnl: Number(row.realized_pnl), timestamp: String(row.timestamp) })); }
export function getTradeForDecision(decisionId: string): Trade | undefined { return getTrades(1000).find((trade) => trade.decisionId === decisionId); }
export function getPositions(): Position[] { return (db.prepare('SELECT * FROM positions WHERE quantity > 0 ORDER BY symbol').all() as Record<string, unknown>[]).map((row) => { const symbol = String(row.symbol); const quantity = Number(row.quantity); const averageEntry = Number(row.average_entry); const currentPrice = getMarketSnapshot(symbol).price; const marketValue = quantity * currentPrice; return { symbol, quantity, averageEntry, currentPrice, marketValue, unrealizedPnl: (currentPrice - averageEntry) * quantity, pnlPct: ((currentPrice - averageEntry) / averageEntry) * 100 }; }); }
export function getLatestSnapshot(): Record<string, number> { const row = db.prepare('SELECT * FROM portfolio_snapshots ORDER BY id DESC LIMIT 1').get() as Record<string, unknown>; return { portfolioValue: Number(row.portfolio_value), cash: Number(row.cash), investedCapital: Number(row.invested_capital), realizedPnl: Number(row.realized_pnl), unrealizedPnl: Number(row.unrealized_pnl), exposurePct: Number(row.exposure_pct), dailyPnl: Number(row.daily_pnl), drawdown: Number(row.drawdown) }; }
export function getPortfolioSummary(): PortfolioSummary {
  const snapshot = getLatestSnapshot();
  const trades = getTrades(1000).filter((trade) => trade.status === 'FILLED');
  const wins = trades.filter((trade) => trade.realizedPnl > 0).length;
  const positions = getPositions();
  const investedCapital = positions.reduce((sum, position) => sum + position.marketValue, 0);
  const unrealizedPnl = positions.reduce((sum, position) => sum + position.unrealizedPnl, 0);
  const portfolioValue = snapshot.cash + investedCapital;
  const totalPnl = snapshot.realizedPnl + unrealizedPnl;
  return {
    startingValue: 100000,
    portfolioValue,
    cash: snapshot.cash,
    investedCapital,
    totalPnl,
    realizedPnl: snapshot.realizedPnl,
    unrealizedPnl,
    todayPnl: totalPnl,
    exposurePct: portfolioValue ? investedCapital / portfolioValue * 100 : 0,
    positionsCount: positions.length,
    winRate: trades.length ? (wins / trades.length) * 100 : 0,
    maxDrawdown: Math.max(snapshot.drawdown, Math.max(0, (100000 - portfolioValue) / 1000)),
    tradeCount: trades.length,
  };
}
export function getAudit(limit = 100): AuditLog[] { return (db.prepare('SELECT * FROM audit_logs ORDER BY timestamp DESC LIMIT ?').all(limit) as Record<string, unknown>[]).map((row) => ({ id: String(row.id), eventId: row.event_id ? String(row.event_id) : undefined, stage: String(row.stage), title: String(row.title), detail: String(row.detail), status: row.status as AuditLog['status'], metadata: row.metadata ? JSON.parse(String(row.metadata)) : undefined, timestamp: String(row.timestamp) })); }
export function getPerformance(): { equity: Array<{ timestamp: string; value: number; dailyPnl: number }>; exposure: Array<{ timestamp: string; exposure: number }>; distribution: Array<{ label: string; value: number }>; metrics: ReturnType<typeof getPortfolioSummary> & { sharpeLike: number; averageTrade: number } } { const snapshots = db.prepare('SELECT * FROM portfolio_snapshots ORDER BY id ASC LIMIT 100').all() as Record<string, unknown>[]; const summary = getPortfolioSummary(); const trades = getTrades(1000).filter((trade) => trade.status === 'FILLED'); const wins = trades.filter((trade) => trade.realizedPnl > 0).length; const losses = trades.filter((trade) => trade.realizedPnl <= 0).length; return { equity: snapshots.map((row) => ({ timestamp: String(row.timestamp), value: Number(row.portfolio_value), dailyPnl: Number(row.daily_pnl) })), exposure: snapshots.map((row) => ({ timestamp: String(row.timestamp), exposure: Number(row.exposure_pct) })), distribution: [{ label: 'Winning trades', value: wins }, { label: 'Losing trades', value: losses }], metrics: { ...summary, sharpeLike: summary.tradeCount ? Number((summary.totalPnl / 100000 / Math.max(0.01, summary.maxDrawdown / 100 + 0.02)).toFixed(2)) : 0, averageTrade: trades.length ? trades.reduce((sum, trade) => sum + trade.realizedPnl, 0) / trades.length : 0 } }; }
export function getMarketData(): MarketSnapshot[] { return SUPPORTED_SYMBOLS.map((symbol) => getMarketSnapshot(symbol)); }
export function saveEventAudit(event: MarketEvent, runId = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`): void { db.prepare('INSERT INTO audit_logs (id, event_id, stage, title, detail, status, metadata, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run(`audit-${runId}-event`, event.id, 'EVENT_DETECTED', 'Event detected', `${event.title} · ${event.affectedSymbols.join(', ')}`, 'INFO', JSON.stringify(event), event.timestamp); }
export function addAudit(log: AuditLog): void { db.prepare('INSERT INTO audit_logs (id, event_id, stage, title, detail, status, metadata, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run(log.id, log.eventId ?? null, log.stage, log.title, log.detail, log.status, log.metadata ? JSON.stringify(log.metadata) : null, log.timestamp); }
export function saveDecision(decision: AgentDecision): void { db.prepare('INSERT INTO agent_decisions (id, event_id, symbol, action, confidence, event_impact, time_horizon, thesis, risk_factors, suggested_position_percent, stop_loss_percent, take_profit_percent, rationale, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(decision.id, decision.eventId, decision.symbol, decision.action, decision.confidence, decision.eventImpact, decision.timeHorizon, decision.thesis, JSON.stringify(decision.riskFactors), decision.suggestedPositionPercent, decision.stopLossPercent, decision.takeProfitPercent, decision.rationale, decision.createdAt); }
export function saveRisk(id: string, decisionId: string, risk: RiskCheck): void { db.prepare('INSERT INTO risk_checks (id, decision_id, status, risk_score, reasons, checks, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)').run(id, decisionId, risk.status, risk.riskScore, JSON.stringify(risk.reasons), JSON.stringify(risk.checks), risk.createdAt); }
export function getLatestRisk(): RiskCheck | undefined { const row = db.prepare('SELECT * FROM risk_checks ORDER BY created_at DESC LIMIT 1').get() as Record<string, unknown> | undefined; return row ? { id: String(row.id), decisionId: row.decision_id ? String(row.decision_id) : undefined, status: row.status as RiskCheck['status'], riskScore: Number(row.risk_score), reasons: JSON.parse(String(row.reasons)), checks: JSON.parse(String(row.checks)), createdAt: String(row.created_at) } : undefined; }
export function getRiskForDecision(decisionId: string): RiskCheck | undefined { const row = db.prepare('SELECT * FROM risk_checks WHERE decision_id = ? ORDER BY created_at DESC LIMIT 1').get(decisionId) as Record<string, unknown> | undefined; return row ? { id: String(row.id), decisionId: row.decision_id ? String(row.decision_id) : undefined, status: row.status as RiskCheck['status'], riskScore: Number(row.risk_score), reasons: JSON.parse(String(row.reasons)), checks: JSON.parse(String(row.checks)), createdAt: String(row.created_at) } : undefined; }
export function hasRecentOrder(eventId: string, symbol: string, minutes = 30): boolean { const row = db.prepare("SELECT COUNT(*) as count FROM orders o JOIN agent_decisions d ON d.id = o.decision_id WHERE o.symbol = ? AND d.event_id = ? AND o.status = 'FILLED' AND o.timestamp > datetime('now', ?)").get(symbol, eventId, `-${minutes} minutes`) as { count: number }; return row.count > 0; }
export function saveMarketSnapshot(snapshot: MarketSnapshot): void { db.prepare('INSERT INTO market_snapshots (symbol, timestamp, price, change_pct, volume, volatility, trend, momentum, moving_average, rsi, recent_changes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(snapshot.symbol, snapshot.timestamp, snapshot.price, snapshot.changePct, snapshot.volume, snapshot.volatility, snapshot.trend, snapshot.momentum, snapshot.movingAverage, snapshot.rsi, JSON.stringify(snapshot.recentChanges)); }
export function getStatus(status: AgentStatus): AgentStatus { return status; }
